# Generated by Django 6.0.5 on 2026-05-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.CharField(blank=True, help_text='Format: owner/repo (e.g. PuneethKrishnaS/SoftMade)', max_length=255, null=True),
        ),
    ]
