# Generated by Django 6.0.5 on 2026-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_advance_payment_project_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='college_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
    ]
