# Generated by Django 6.0.5 on 2026-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_group_remove_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default='Payment', max_length=255, null=True),
        ),
    ]
